AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Sample SAM Template for sam-app

Resources:
  fullLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ""
      Handler: app.lambda_handler
      Runtime: python3.10
      Architectures:
        - x86_64
